FROM docker-config-engine-buster

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y g++ python3-dev libxml2 libcurl3-gnutls libcjson-dev libltdl-dev 

RUN pip3 install connexion==2.7.0 \
                 setuptools==21.0.0 \
                 grpcio-tools==1.20.0 \
                 certifi==2017.4.17 \
                 python-dateutil==2.6.0 \
                 six==1.11.0 \
                 urllib3==1.21.1

COPY \
{% for deb in docker_pensando_sw_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
debs/

RUN dpkg -i \
{% for deb in docker_pensando_sw_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor %}


COPY template_nmd.json /tmp/

COPY template_fru.json /tmp/

COPY fru.json /tmp/
COPY fru.json /usr/bin/
COPY netagentcfg.sh /usr/bin/
COPY netagenthal.sh /usr/bin/
COPY nmd.sh /usr/bin/
COPY models/ /usr/models/yang/

COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

RUN mkdir -p /pensando/hostdir &&\
    rm -rf /nic/tools
env NAPLES_PIPELINE apollo
env PDS_HOST 0.0.0.0
env HOST_NAME vnaples1
env CONTROLLER 0.0.0.0
env MAC_ADDR   00:00:00:00:00:00
env SERIAL_NUM REPLACE_ME
env SONIC_MODE 1
env EVENTS_DIR /pensando/events

RUN apt-get remove -y g++ python3-dev
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /debs

## TODO: symbolic links will be removed when AAA improvements get merged
RUN ln -sf /host_etc/passwd /etc/passwd	
RUN ln -sf /host_etc/group /etc/group


ENTRYPOINT ["/usr/local/bin/supervisord"]
