# Pensando Platform modules

PENSANDO_TAORMINA_PLATFORM_MODULE_VERSION = 1.0

export PENSANDO_TAORMINA_PLATFORM_MODULE_VERSION

PENSANDO_TAORMINA_PLATFORM_MODULE = sonic-platform-pensando-taormina_$(PENSANDO_TAORMINA_PLATFORM_MODULE_VERSION)_amd64.deb
$(PENSANDO_TAORMINA_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-pensando
$(PENSANDO_TAORMINA_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(PENSANDO_TAORMINA_PLATFORM_MODULE)_PLATFORM = x86_64-pensando_taormina-r0
SONIC_DPKG_DEBS += $(PENSANDO_TAORMINA_PLATFORM_MODULE)


$(eval $(call add_extra_package,$(PENSANDO_TAORMINA_PLATFORM_MODULE)))
