# docker image for pensando-sw

DOCKER_PENSANDO_SW_STEM = docker-pensando-sw
DOCKER_PENSANDO_SW = $(DOCKER_PENSANDO_SW_STEM).gz
#DOCKER_PENSANDO_SW_DBG = $(DOCKER_PENSANDO_SW_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_PENSANDO_SW)_PATH = $(DOCKERS_PATH)/$(DOCKER_PENSANDO_SW_STEM)

$(DOCKER_PENSANDO_SW)_DEPENDS += $(PENSANDO_SW)
#$(DOCKER_PENSANDO_SW)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_DEPENDS)
#$(DOCKER_PENSANDO_SW)_DBG_DEPENDS += $(PENSANDO_SW_DBG)

SONIC_DOCKER_IMAGES += $(DOCKER_PENSANDO_SW)
$(DOCKER_PENSANDO_SW)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BUSTER)

$(DOCKER_PENSANDO_SW)_VERSION = 1.0.0
$(DOCKER_PENSANDO_SW)_PACKAGE_NAME = pensando-sw

#$(DOCKER_PENSANDO_SW)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

#ifeq ($(INCLUDE_MGMT_FRAMEWORK), y)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_PENSANDO_SW)
#endif

#SONIC_DOCKER_DBG_IMAGES += $(DOCKER_PENSANDO_SW_DBG)
#ifeq ($(INCLUDE_MGMT_FRAMEWORK), y)
#SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_PENSANDO_SW_DBG)
#endif

$(DOCKER_PENSANDO_SW)_CONTAINER_NAME = pensando-sw
$(DOCKER_PENSANDO_SW)_RUN_OPT += --privileged -t
$(DOCKER_PENSANDO_SW)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_PENSANDO_SW)_RUN_OPT += -v /etc:/host_etc:ro
$(DOCKER_PENSANDO_SW)_RUN_OPT += -v /var/run/dbus:/var/run/dbus:rw
$(DOCKER_PENSANDO_SW)_RUN_OPT += --mount type=bind,source="/var/platform/",target="/mnt/platform/"

#$(DOCKER_PENSANDO_SW)_BASE_IMAGE_FILES += sonic-cli:/usr/bin/sonic-cli
